name: tests
on: [push, pull_request]
jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "Alpine Edge"
            runner: ubuntu-latest
            container: alpine-edge
          - name: "Alpine Latest"
            runner: ubuntu-latest
            container: alpine-latest
          - name: "Archlinux Base"
            runner: ubuntu-latest
            container: archlinux
          - name: "Centos Stream9"
            runner: ubuntu-latest
            container: centos-stream9
          - name: "Debian Stable"
            runner: ubuntu-latest
            container: debianstable
# Pause testing on debian testing until libfiu-dev/fiu-utils is available
#          - name: "Debian Testing"
#            runner: ubuntu-latest
#            container: debiantesting
          - name: "Fedora 37"
            runner: ubuntu-latest
            container: fedora37
          - name: "Fedora 38"
            runner: ubuntu-latest
            container: fedora38
          - name: "OpenSUSE Leap"
            runner: ubuntu-latest
            container: opensuseleap
          - name: "OpenSUSE Tumbleweed"
            runner: ubuntu-latest
            container: opensusetumbleweed
          - name: "Ubuntu 18.04"
            runner: ubuntu-latest
            container: ubuntu1804
          - name: "Ubuntu 20.04"
            runner: ubuntu-latest
            container: ubuntu2004
          - name: "Ubuntu 22.04"
            runner: ubuntu-latest
            container: ubuntu2204
          - name: "macOS 12"
            runner: macos-12
            container: osx-12
          - name: "macOS 13"
            runner: macos-13
            container: osx-13
          - name: "macOS 14"
            runner: macos-14
            container: osx-14
    runs-on: ${{ matrix.runner }}
    continue-on-error: ${{ matrix.continue-on-error == true }}
    steps:
      - uses: actions/checkout@v4
      - name: Build ${{ matrix.name }}
        env:
          DOCKER_REGISTRY: docker.pkg.github.com
          DOCKER_CACHE_IMAGE: docker.pkg.github.com/${{ github.repository }}/timewarrior_cache
          GITHUB_USER: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONTAINER: ${{ matrix.container }}
        run: if [[ !( "${CONTAINER}" =~ osx-* ) ]] ; then docker compose build "test-${CONTAINER}" ; fi
      - name: Test ${{ matrix.name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONTAINER: ${{ matrix.container }}
        run: if [[ !( "${CONTAINER}" =~ osx-* ) ]]; then docker compose run "test-${CONTAINER}" ; else bash test/scripts/test_osx.sh ; fi
